### ISSUE TITLE
session error

### ISSUE THREAD

**Issue by BruceHan98** [aidewoode/black_candy#111]
I deployed balck candy with docker-composer and it works well when I visit it via my ip address. However, after binding my domain name and ip address using nginx, I am stuck on the login page with a "422 Unprocessable Entity" error when accessing the website via the domain name, but it works well via my ip address. I think it is a seesion error but I can't get it through. Any help will be appreciated!

**Comment by aidewoode** [comment]
Hi, please post your nginx config and docker-compose file,  so I can check if there is an issue with the config file. If you can get the error log of black candy, please post it too. Thanks

**Comment by BruceHan98** [comment]
Thanks for your reply. Here is the configs and logs.

The **docker-compose.yml**:
```yaml
version: '3.4'
services:
  app: &app_base
    container_name: 'blackcandy_app'
    image: blackcandy/blackcandy
    volumes:
      - ./log:/app/log
      - /media_data:/media_data
      - production_uploads_data:/app/public/uploads
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      REDIS_CACHE_URL: redis://redis:6379/1
      REDIS_SIDEKIQ_URL: redis://redis:6379/2
      MEDIA_PATH: /media_data
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: 'blackcandy_postgres'
    image: postgres:11.1-alpine
    volumes:
      - production_db_data:/var/lib/postgresql/data
  redis:
    container_name: 'blackcandy_redis'
    image: redis:4.0-alpine
    volumes:
      - production_redis_data:/data
  worker:
    container_name: 'blackcandy_worker'
    <<: *app_base
    command: bundle exec sidekiq
  web:
    container_name: 'blackcandy_web'
    <<: *app_base
    depends_on:
      - app
      - worker
    ports:
      - 8000:80
    command: nginx -g 'pid /tmp/nginx.pid; daemon off;'
volumes:
  production_db_data:
  production_redis_data:
  production_uploads_data:
```

The nginx.conf:
```
# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
    multi_accept on;
    use epoll;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 4096;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80;
        # listen       [::]:80;
        server_name  brucehan.club;
        # root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        error_page 404 /404.html;
        location = /404.html {
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        }

        location / {
            proxy_pass http://127.0.0.1:8000;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
```

and, the **production.log** is filled with these following lines:
```
I, [2021-12-01T05:42:16.887552 #10]  INFO -- : [d08978f0-9086-4b8d-a3fc-b6dd25b2bb4f] Started GET "/" for 159.75.198.66 at 2021-12-01 05:42:16 +0000
I, [2021-12-01T05:42:16.888155 #10]  INFO -- : [d08978f0-9086-4b8d-a3fc-b6dd25b2bb4f] Processing by HomeController#index as HTML
I, [2021-12-01T05:42:16.889916 #10]  INFO -- : [d08978f0-9086-4b8d-a3fc-b6dd25b2bb4f] Redirected to http://brucehan.club/session/new
I, [2021-12-01T05:42:16.889998 #10]  INFO -- : [d08978f0-9086-4b8d-a3fc-b6dd25b2bb4f] Filter chain halted as :require_login rendered or redirected
I, [2021-12-01T05:42:16.890082 #10]  INFO -- : [d08978f0-9086-4b8d-a3fc-b6dd25b2bb4f] Completed 302 Found in 2ms (ActiveRecord: 0.2ms | Allocations: 325)
```

Looking forward to your reply！
