### ISSUE TITLE
No Music Discovered

### ISSUE THREAD

**Issue by hughesjs** [aidewoode/black_candy#53]
I'm using docker to give this a go but unfortunately, no music is discovered.

Here's my slightly modified compose file:

```
version: '3.4'
networks:
        reverse-proxy:
                external: true
        blackcandy:
                external: false
services:
  app: &app_base
    container_name: 'app'
    image: blackcandy/blackcandy
    volumes:
      - ./log:/app/log
      - /datapool/media/music:/media_data
      - /datapool/media/uploads:/app/public/uploads
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      REDIS_DATA_URL: redis://redis:6379/0
      REDIS_CACHE_URL: redis://redis:6379/1
      REDIS_SIDEKIQ_URL: redis://redis:6379/2
      MEDIA_PATH: /media_data
      SECRET_KEY_BASE: redacted
    depends_on:
      - postgres
      - redis
    networks:
      - blackcandy
  postgres:
    container_name: 'blackcandy_postgres'
    image: postgres:11.1-alpine
    volumes:
      - production_db_data:/var/lib/postgresql/data
    networks:
      - blackcandy
  redis:
    container_name: 'blackcandy_redis'
    image: redis:4.0-alpine
    volumes:
      - production_redis_data:/data
    networks:
      - blackcandy
  worker:
    container_name: 'blackcandy_worker'
    <<: *app_base
    command: bundle exec sidekiq
    networks:
      - blackcandy
  web:
    container_name: 'blackcandy_web'
    <<: *app_base
    depends_on:
      - app
      - worker
    command: nginx -g 'pid /tmp/nginx.pid; daemon off;'
    networks:
      - reverse-proxy
      - blackcandy
volumes:
  production_db_data:
  production_redis_data:
  production_uploads_data:
```

I've connected using docker-exec and all of my music is showing up in /media_data as I would have expected so I'm not sure what's going wrong. There's nothing obvious in the logs either.

Please advise?
